[project]
name = "game_database"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = [
    "colorlog",
    "prompt_toolkit",
]

[tool.uv]
index-url = "https://pypi.tuna.tsinghua.edu.cn/simple/"
